<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-10-11T21:52:09-03:00" hostname="https://na139.salesforce.com" tests="1" failures="1"  errors="0"  time="0.18">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Oct 11, 2020 9:52 PM"/>
            <property name="testExecutionTime" value="0.18 s"/>
            <property name="testTotalTime" value="0.18 s"/>
            <property name="commandTime" value="5.33 s"/>
            <property name="hostname" value="https://na139.salesforce.com"/>
            <property name="orgId" value="00D4W000006i8LzUAI"/>
            <property name="username" value="liciavereda.testetopi@devorg.com"/>
            <property name="testRunId" value="7074W0000886zxZ"/>
            <property name="userId" value="0054W00000BfbMbQAJ"/>
        </properties>
        <testcase name="filterAccountsByCpfTeste" classname="AccountFilterTeste" time="0.18">
            <failure message="System.AssertException: Assertion Failed: Same value: 1"><![CDATA[Class.AccountFilterTeste.filterAccountsByCpfTeste: line 67, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
