<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-10-11T21:35:20-03:00" hostname="https://na139.salesforce.com" tests="1" failures="1"  errors="0"  time="0.07">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Oct 11, 2020 9:35 PM"/>
            <property name="testExecutionTime" value="0.07 s"/>
            <property name="testTotalTime" value="0.07 s"/>
            <property name="commandTime" value="5.4 s"/>
            <property name="hostname" value="https://na139.salesforce.com"/>
            <property name="orgId" value="00D4W000006i8LzUAI"/>
            <property name="username" value="liciavereda.testetopi@devorg.com"/>
            <property name="testRunId" value="7074W0000886zHz"/>
            <property name="userId" value="0054W00000BfbMbQAJ"/>
        </properties>
        <testcase name="filterAccountsByCpfTest" classname="AccountFilterTeste" time="0.07">
            <failure message="System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, InvÃ¡lido: [Cnpj__c]"><![CDATA[Class.AccountFixtureFactory.createAccount: line 46, column 1
Class.AccountFixtureFactory.createAccount: line 40, column 1
Class.AccountFilterTeste.filterAccountsByCpfTest: line 46, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
